language: go

go:
    - 1.5
    - 1.6
    - tip

before_install:
    - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.11.tar.gz
    - tar -xvf libsodium-1.0.11.tar.gz
    - cd libsodium-1.0.11
    - ./configure && make && sudo make install

sudo: required
