language: go

go:
    - 1.5
    - 1.6
    - tip

install:
    - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.11.tar.gz -P /tmp
    - tar -xvf -C /tmp/ /tmp/libsodium-1.0.11.tar.gz
    - cd /tmp/libsodium-1.0.11
    - ./configure && make && make install

sudo: required
